name: Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: ./install-all.sh
    - name: Run ESLint
      run: ./lint-all.sh
